org: acrboleda
app: zemoga-serverless-portfolio-web-app
service: zemoga-serverless-portfolio-web-app
frameworkVersion: '2'

custom:
  tableName: 'users-table-${sls:stage}'
  dynamodb:
  # If you only want to use DynamoDB Local in some stages, declare them here
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      heapInitial: 200m
      heapMax: 1g
      migrate: true
      seed: true
      convertEmptyValues: true
  bundle:
    packager: yarn

package:
  patterns:
    - 'dist/**'
    - 'package.json'
    - 'yarn.lock'
    #- '!node_modules/**'
    - '!src/**'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: '20201221'
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            - dynamodb:DeleteItem
          Resource:
            - Fn::GetAtt: [ UsersTable, Arn ]
  environment:
    USERS_TABLE: ${self:custom.tableName}

functions:
  api:
    handler: dist/index.handler
    events:
      - httpApi: '*'

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: TWITTER_HANDLE
            AttributeType: S
        KeySchema:
          - AttributeName: TWITTER_HANDLE
            KeyType: HASH
        BillingMode: PAY_PER_REQUEST
        TableName: ${self:custom.tableName}

plugins:
  #- serverless-bundle
  - serverless-dynamodb-local
  - serverless-offline