import styles from '../styles/Home.module.css';
import { useEffect, useState } from 'react';
import { Button, InputAdornment, TextField } from '@mui/material';
import type { NextPage } from 'next';
import { useRouter } from 'next/router';
import Head from 'next/head';
import Footer from '../components/Footer';

const Home: NextPage = () => {
  const [twitterHandle, setTwitterHandle] = useState('');
  const [buttonDisabled, setButtonDisabled] = useState(true);
  const router = useRouter();

  useEffect(() => {
    setButtonDisabled(twitterHandle.trim().length >= 4 ? false : true);
  }, [twitterHandle, buttonDisabled])

  const onGo = () => router.push(`/profile/${twitterHandle}`);

  return (
    <div className={styles.container}>
      <Head>
        <title>Serverless Portfolio Web App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Serverless Portfolio Web App
        </h1>

        <p className={styles.description}>
          Let get started by giving your <code className={styles.code}>Twitter handle</code>
        </p>

        <TextField
          id="outlined-start-adornment"
          sx={{ m: 1, width: '25ch' }}
          label="Twitter handle"
          placeholder="cfarboleda"
          value={twitterHandle}
          onChange={event => setTwitterHandle(event.target.value)}
          InputProps={{
            startAdornment: <InputAdornment position="start">@</InputAdornment>,
          }}
        />
        <Button variant="text"
          disabled={buttonDisabled}
          onClick={onGo}>Go &rarr;</Button>
      </main>

      <Footer/>
    </div>
  )
}

export default Home
