import styles from '../../styles/Error.module.css';
import { Link } from '@mui/material';
import type { NextPage } from 'next';
import Head from 'next/head';
import Footer from '../../components/Footer';

const NotFoundPage: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Serverless Portfolio Web App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
        404
        </h1>

        <p className={styles.description}>
          Twitter handle not found
        </p>

        <Link href="/">
          Try again
        </Link>
      </main>

      <Footer/>
    </div>
  )
}

export default NotFoundPage